apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello from Nginx</title>
    </head>
    <body>
      <h1>It works! Deployed via Argo CD 🚀</h1>
    </body>
    </html>

